apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-terminal
  labels:
    app: ai-terminal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-terminal
  template:
    metadata:
      labels:
        app: ai-terminal
    spec:
      containers:
      - name: ai-terminal
        image: dockerbabuli/ai-terminal:arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 80
     
