// filepath: k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-terminal
  labels:
    app: ai-terminal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-terminal
  template:
    metadata:
      labels:
        app: ai-terminal
    spec:
      containers:
      - name: ai-terminal
        image: dockerbabuli/ai-terminal:ed0a7024cb3217ef56dd4d391072f389db5d4986
        ports:
        - containerPort: 80